# config/routes.yaml

controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\LoginController::login

professor:
    path: /professor
    controller: App\Controller\ProfessorController::index

trainee:
    path: /trainee
    controller: App\Controller\TraineeController::index